Phase02 refactor
Star-Academy/Winter99-Codestar-Reza-Adibi pull request #2
Opened 2021-02-24 17:23 UTC by RAAvenger

2021-02-24 18:34 UTC, MKasaei00 commented on Phase-01/Filterer.java
> +    public static HashSet<String> AndWords(InvertedIndex invertedIndex, HashSet<String> initialSet, ArrayList<String> words) throws Exception {
نام تابع باید با اسم کوچک شروع شود

2021-02-24 18:35 UTC, MKasaei00 commented on Phase-01/Filterer.java
> +    public static HashSet<String> FilterDocIDs(InvertedIndex invertedIndex, Map<String, ArrayList<String>> filters) {
نام تابع با حرف کوچک

2021-02-24 18:58 UTC, MKasaei00 commented on Phase-01/Filterer.java
>              return null;
شرط ها را میشه با هم ترکیب کرد

2021-02-24 18:58 UTC, RAAvenger commented on Phase-01/Filterer.java
> +    public static HashSet<String> AndWords(InvertedIndex invertedIndex, HashSet<String> initialSet, ArrayList<String> words) throws Exception {
https://google.github.io/styleguide/cppguide.html#Function_Names

2021-02-24 18:59 UTC, RAAvenger commented on Phase-01/Filterer.java
>              return null;
میشه نمونه کد بنویسی؟

2021-02-24 18:59 UTC, MKasaei00 commented on Phase-01/Main.java
> +    Scanner scanner = new Scanner(System.in);
فراخوانی 
‍‍‍‍`scanner.close()`

2021-02-24 19:34 UTC, MKasaei00 commented on Phase-01/Filterer.java
>              return null;
`if (invertedIndex == null || invertedIndex.IsEmpty() || initialSet == null || initialSet.isEmpty())`

2021-02-24 19:38 UTC, MKasaei00 commented on Phase-01/Filterer.java
> +    public static HashSet<String> AndWords(InvertedIndex invertedIndex, HashSet<String> initialSet, ArrayList<String> words) throws Exception {
فکر می‌کنم تو جاوا مرسوم هست که اسم متود‌ها با حرف کوچک شروع بشه 
باز بقیه هم نظر بدن

2021-02-24 19:43 UTC, MKasaei00 commented on Phase-01/InvertedIndex.java
> +        return (HashSet<String>) allDocIDs;
down casting غیر اصولی

به نظرم باید متغییر به صورت 
`HashSet`
تعریف بشه

2021-02-24 19:48 UTC, MKasaei00 commented on Phase-01/Main.java
> +                    break;
اگر مقدار رشته‌ها به صورت ثابت تعریف بشن تمیزتر میشه

2021-02-24 19:57 UTC, MKasaei00 commented on Phase-01/Main.java
>          Main This = new Main();
می‌توان توابعی که از تابع اصلی فراخوانی می‌شوند را به صورت 
`static`
تعریف کنیم و نیاز به ساخت شی از کلاس فعلی نخواهد بود.

2021-02-25 05:01 UTC, mohammadhheidarzade approved these changes
سلام خسته نباشید کد خوبی بود
نکته ای که هست فایل های data
معمولا در فایل .gitignore
قرار میگیره توصیه میکنم دربارش مطالعه کنی
فایل های .class
هم نباید در گیت باشه که این ها هم میتونن در فایل .gitignre 
قرار بگیرند
سایت https://www.toptal.com/developers/gitignore
هم میتونه در تولید gitignore کمک کنه

2021-02-25 11:26 UTC, RAAvenger commented
> 
> 
> سلام خسته نباشید کد خوبی بود
> نکته ای که هست فایل های data
> معمولا در فایل .gitignore
> قرار میگیره توصیه میکنم دربارش مطالعه کنی
> فایل های .class
> هم نباید در گیت باشه که این ها هم میتونن در فایل .gitignre
> قرار بگیرند
> سایت https://www.toptal.com/developers/gitignore
> هم میتونه در تولید gitignore کمک کنه

از گیت ایگنور استفاده کردم اینجا، فایل‌هایی که گفتی رو هم بهش اضافه میکنم.

2021-02-25 12:32 UTC, MKasaei00 commented on Phase-01/Main.java
> +        final Scanner scanner = new Scanner(System.in);
از نظر اصولی بعد از اتمام کار برنامه با 
scanner 
لازمه بسته بشه

2021-02-25 12:33 UTC, MKasaei00 approved these changes
خسته نباشی
مشکل تابع ایستا حل شد

2021-02-25 12:34 UTC, MKasaei00 approved these changes

2021-02-25 12:41 UTC, RAAvenger commented on Phase-01/Main.java
> +        final Scanner scanner = new Scanner(System.in);
درسته
ولی از اونجایی که اینجا تاثیر چندانی روی بهینگی برنامه نداره ترجیح میدم که این کار رو  برای نظم دادن در اخر تابع انجام بدم

2021-02-25 12:43 UTC, MKasaei00 commented
در مورد نام توابع که با حرف کوچک باشه یا نه
بهترین مرجع کلاس‌های آرایه و مپ هست که در خود جاوا تعریف شده و ما استفاده می‌کنیم
تمام متود‌ها با حرف کوچک شروع می‌شوند و به صورت 
camelCase 
هستند.

2021-02-25 12:56 UTC, MKasaei00 commented on Phase-01/Main.java
> +        final Scanner scanner = new Scanner(System.in);
منظورم اینه که دستور 
scanner.close()
که برای بستن فایل ورودی از ترمینال هست بهتره اضافه بشه

2021-02-25 20:30 UTC, MRSadeghi78 reviewed
در کل خیلی کد تمیزی بود
فقط یه نکته‌ای هست که کد تو هم مثل محمد خیلی کامنت زیاد داره
اگه بعضی جاها(مثلا تابع هایی که از اسمشون معلومه چیکار میکنن) کامنت‌ها رو کمتر کنی فکر میکنم کدت خلوتتر میشه و اینجوری خواناییش هم بیشتر میشه

2021-02-25 20:30 UTC, MRSadeghi78 commented on Phase-01/Filterer.java
> +    public static HashSet<String> OrWords(InvertedIndex invertedIndex, HashSet<String> initialSet, ArrayList<String> words) throws Exception {
توی این کلاس، تقریبا همه توابع یه پارامتر
invertedIndex
دارن، به نظرم بهتره اون رو یه فیلد جدا توی کلاست در نظر بگیری تا مجبور نباشی به همه تابع ها پاس بدیش.

2021-02-25 20:30 UTC, MRSadeghi78 commented on Phase-01/Filterer.java
> +            }
تعداد شرط ها اینجا یه ذره زیاده
به نظرم بهتره چندتا کامنت بذاری که هر شرط(مخصوصا اون پایینی ها) چیکار میکنن
یا اینکه خود تابع رو به چندتا تابع مختلف تقسیم کنی

2021-02-25 20:30 UTC, MRSadeghi78 commented on Phase-01/Filterer.java
> +    public static HashSet<String> AndWords(InvertedIndex invertedIndex, HashSet<String> initialSet, ArrayList<String> words) throws Exception {
منم با محمد درمورد اینکه اسم تابع ها باید با حروف کوچک شروع بشه موافقم
البته که اجباری نیست ولی فکر میکنم عرفش اینطوری باشه

2021-02-25 20:30 UTC, MRSadeghi78 commented on Phase-01/InvertedIndex.java
> +    private final HashSet<String> allDocIDs;
این خط رو هم نمیفهمم، چرا آیدی همه داکیومنت ها رو نگه میداری؟

2021-02-25 20:42 UTC, MKasaei00 commented on Phase-01/InvertedIndex.java
> +    private final HashSet<String> allDocIDs;
منم متوجه نشدم

2021-02-26 05:42 UTC, alrz1999 commented on Phase-01/Filterer.java
> +    public static HashSet<String> AndWords(InvertedIndex invertedIndex, HashSet<String> initialSet, ArrayList<String> words) throws Exception {
اجبار هم هست 😁

2021-02-26 06:25 UTC, alrz1999 requested changes

2021-02-26 06:25 UTC, alrz1999 commented on Phase-01/Main.java
> +        Map<String, String> result = reader.readAllFileInFolder("EnglishData");
یه فیلد استاتیک بشه بهتره

2021-02-26 06:25 UTC, alrz1999 commented on Phase-01/InvertedIndex.java
>          String[] words = content.toLowerCase().split("\\W+");
این کار ربطی به
invertedindex
نداره و برای تبدیل ورودی به
token
ها بهتره یه کلاس دیگه زده بشه

2021-02-26 06:25 UTC, alrz1999 commented on Phase-01/Main.java
> +        String[] rawWords = userInput.toLowerCase().split("[, .]");
این رشته های ثابت بهتره به صورت یه 
فیلد استاتیک تعریف بشن تا سریع تر قابل شناسایی  باشن و اینکه بشه جاهای دیگه هم ازشون استفاده کرد مثلا
رجکسی که برای جدا کردن کلمه های داکیومنت به کار میره میتونه برای جدا کردن ورودی کاربر هم استفاده بشه

2021-02-26 06:25 UTC, alrz1999 commented on Phase-01/Main.java
> +        words.put("and", new ArrayList<>());
این کار شاید الان جواب بده ولی وقتی کد بیشتر میشه و فیچرهای بیشتری میخوایم مشکل ایجاد میکنه
هم اینکه مخالف
OOP
هم هست

2021-02-26 06:25 UTC, alrz1999 commented on Phase-01/Filterer.java
>  public class Filterer {
به نظرم این کلاس یه مقدار بزرگ شده

2021-02-26 12:14 UTC, RAAvenger commented on Phase-01/Filterer.java
> +    public static HashSet<String> OrWords(InvertedIndex invertedIndex, HashSet<String> initialSet, ArrayList<String> words) throws Exception {
توابع استاتیک هستن که اگر یه وقتی چندتا 
invertedIndex
داشتیم ساده تر بشه از هر تابع استفاده کرد.

2021-02-26 12:16 UTC, RAAvenger commented on Phase-01/InvertedIndex.java
> +    private final HashSet<String> allDocIDs;
برای وقتی که میخوایم فقط عمل 
not
رو داشته باشیم، اونجا باید همه‌ی داکیومنت‌ها منهای یه تعدادی رو پیاده سازی کنیم که برای اینکار اگر من ای‌دی همه داکیومنت‌ها رو نگهدارم کم هزینه تره.

2021-02-26 12:18 UTC, RAAvenger commented on Phase-01/InvertedIndex.java
>          String[] words = content.toLowerCase().split("\\W+");
موافقم، ولی توی این مرحله به نظرم رسید که شاید لازم نشه و در مراحل بعدی یه کلاس جامع برای اینکار بزنم.

2021-02-27 13:09 UTC, MKasaei00 commented on Phase-01/Main.java
>          TextFileReader reader = new TextFileReader();
اگر متود‌های تابع به صورت استاتیک تعریف بشه نیازی به ساخت شی نیست

2021-02-27 13:09 UTC, MKasaei00 commented on Phase-01/Main.java
>          Map<String, String> result = reader.readAllFileInFolder("EnglishData");
می‌تونه فاینال تعریف بشه

2021-02-27 13:58 UTC, MKasaei00 commented on Phase-01/Main.java
>          Map<String, ArrayList<String>> filters = GetFiltersFromUser();
می‌تونه فاینال تعریف بشه

2021-02-27 14:00 UTC, MKasaei00 approved these changes

2021-02-27 20:21 UTC, alrz1999 approved these changes

2021-02-28 15:32 UTC, merged