(phase 03)feature/unit test
Star-Academy/Winter99-Codestar-Reza-Adibi pull request #3
Opened 2021-03-02 16:53 UTC by RAAvenger

2021-03-03 14:36 UTC, MKasaei00 requested changes
چند مورد بهبود به ذهنم رسید را نوشتم
یک باگ هم در فایل‌ریدر هست کامنت گذاشتم

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/FiltererTest.java
> +        }
برای این قسمت 
میشه به جای اینکه ابتدا بررسی کنیم که استثنا میده یا نه 
در قسمت 
catch
عبارت
assert(false)
را قرار بدیم

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/FiltererTest.java
> +        }
در قسمت‌های دیگه هم بعضا تکرار شده این مسئله

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/InvertedIndexTest.java
> +        assertEquals(correctResult, invertedIndex.invertedIndexMap);
به نظرم بهتره که از توابع استفاده بشه و دسترسی مستقیم به فیلد‌های خصوصی ایجاد نشه

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/main/java/TextFileReader.java
> +            sb.append("\n");
این قسمت یک باگ داره
در صورتی که فایل فقط یک خط داشته باشه.
رشته‌ای که در نهایت از این تابع دریافت می‌شه همان محتوای فایل هست با یک کاراکتر
\n 
اضافه

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/TextFileReaderTest.java
> +        testResult = (HashMap<String, String>) TextFileReader.readAllFileInFolder("data");
این دو خط می‌تونن با هم ادغام بشن

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/main/java/Main.java
> +        System.out.println(searchEngine.filterDocIDs(filters));
متغییر‌ها را میشه فاینال تعریف کرد

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/FiltererTest.java
> +        secondSet.add("john");
این خط ها برای مقداردهی اولیه مجموعه‌ها را میشه با هم ادغام کرد

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/FiltererTest.java
> +    public void notWordsTest() {
به نظرم درست تر هست که تست‌ها در توابع جدا نوشته بشن تا وقتی یک تست پاس نمی‌شه راحت‌تر بشه مشکل را متوجه شد و تست‌ها ریز‌تر کد را بررسی کنند.

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/FiltererTest.java
> +    public void notWordsTest() {
بعضی قسمت‌های دیگه هم این بحث تکرار شده

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/FiltererTest.java
> +        }
بدنه‌ی کلی تست‌ها مشابه هم هست و می‌توان با تعریف یک تابع روند تست و کد‌های تکراری را بسیاری کم کرد

2021-03-03 14:36 UTC, MKasaei00 commented on Project-01/src/test/java/TextFileReaderTest.java
> +        assertEquals(testTextCF, correctFileText);
به نظرم مناسب‌تر هست که تست‌های مختلف در توابع تست مجزا تعریف بشن و هر تابع فقط یک تست کیس را اجرا کنه

2021-03-03 15:00 UTC, RAAvenger commented on Project-01/src/test/java/InvertedIndexTest.java
> +        assertEquals(correctResult, invertedIndex.invertedIndexMap);
اینجا هدف این بوده که از توابع استفاده نشه.

2021-03-03 15:02 UTC, RAAvenger commented on Project-01/src/main/java/TextFileReader.java
> +            sb.append("\n");
این رو موقع تست هندل کردم و توی باقی جاها هم تاثیری نداره.

2021-03-03 15:03 UTC, RAAvenger commented on Project-01/src/test/java/TextFileReaderTest.java
> +        testResult = (HashMap<String, String>) TextFileReader.readAllFileInFolder("data");
هدف تمیزی بوده

2021-03-03 15:04 UTC, RAAvenger commented on Project-01/src/main/java/Main.java
> +        System.out.println(searchEngine.filterDocIDs(filters));
اثر خاصی داره؟

2021-03-03 15:04 UTC, RAAvenger commented on Project-01/src/test/java/FiltererTest.java
> +        secondSet.add("john");
چطور؟

2021-03-03 15:11 UTC, MKasaei00 commented on Project-01/src/main/java/TextFileReader.java
> +            sb.append("\n");
به نظرم بهتره که اصلاح بشه چون ما از این تابع انتظار داریم متن داخل فایل را بده نه چیزی اضافه یا کم
خودم هم این مشکل را داشتم :))

2021-03-03 15:13 UTC, MKasaei00 commented on Project-01/src/main/java/Main.java
> +        System.out.println(searchEngine.filterDocIDs(filters));
در کل اگر متغییر‌ها فاینال بشن یه مقداری در بحث‌های کامپایل و این مسائل بهینه تر میشه

برای همین اصولا وقتی یک متغییر را فقط یک بار مقداردهی می‌کنند و از اون به بعد تغییر نمی‌کنه فاینال تعریف می‌کنند 
ولی اینجا خیلی هم مهم نیست من برای تمیزی یادآوری کردم

2021-03-03 15:15 UTC, MKasaei00 commented on Project-01/src/test/java/FiltererTest.java
> +        secondSet.add("john");
```
        HashSet<String> secondSet = new HashSet<>(
                      Arrays.asList("you" , "know" , "nothing" , "john")
        );
```

2021-03-03 15:38 UTC, mohammadhheidarzade requested changes
تابع های تست خیلی بزرگ هستند
در هر تابع چند assert 
استفاده شده که هر تابع باید یک 
Assert
داشته باشه

2021-03-03 15:38 UTC, mohammadhheidarzade commented on Project-01/src/test/java/ConsoleTest.java
> +    public void getUserInputFiltersTest() {
تابع تست خیلی طولانیه
هر تابع یک assert
باید داشته باشه و بیشتر از اون زیاد جالب نیست

2021-03-04 15:31 UTC, MRSadeghi78 reviewed
تنها نکته‌ای که بود اینه که توابع تست خیلی طولانی هستن و توی اکثرشون بیش از یکبار از
assert
استفاده شده. خوبه که تست ها رو توی توابع جداگانه و کوچکتر بنویسی، اینطوری خود کد هم تمیزتر میشه

2021-03-04 15:31 UTC, MRSadeghi78 commented on Project-01/src/test/java/ConsoleTest.java
> +    public void stringToFilterTest() {
تابع خیلی طولانیه، بهتره به چندتا تابع کوچکتر تقسیم بشه

2021-03-06 19:56 UTC, mohammadhheidarzade approved these changes
خیلی بهتر شد تابع ها کوچیک شدن
خسته نباشید

2021-03-07 08:37 UTC, MKasaei00 approved these changes

2021-03-07 12:48 UTC, alrz1999 approved these changes

2021-03-07 12:48 UTC, alrz1999 commented on Project-01/src/main/java/Console.java
> +    final Scanner scanner;
اینا نمیتونستن 
private
باشن؟
اون رجکس هم به نظر میتونه فاینال باشه

2021-03-07 12:48 UTC, alrz1999 commented on Project-01/src/main/java/Main.java
> +        final Map<String, String> result = TextFileReader.readAllFileInFolder("EnglishData");
path 
به صورت یه فاینال استاتیک باشه بهتر نیست؟
سه خط اول هم برن تو یه تابع قشنگ تره به نظر

2021-03-07 12:48 UTC, alrz1999 commented on Project-01/src/main/java/Main.java
enter
اضافی 😂😅

2021-03-07 12:48 UTC, alrz1999 commented on Project-01/src/main/java/TextFileReader.java
>          FileReader fileReader = null;
چرا
`FileReader fileReader;`
نه؟

2021-03-07 12:48 UTC, alrz1999 commented on Project-01/src/test/java/TextFileReaderTest.java
> +        testResult = (HashMap<String, String>) TextFileReader.readAllFileInFolder("data");
چرا
cast 
شده؟
نمیتونست همون
Map
باشه؟

2021-03-07 12:48 UTC, alrz1999 commented on Project-01/src/test/java/TokenizerTest.java
> +        ArrayList<String> correctResult = new ArrayList<>(Arrays.asList("hello"));
intellij
واسه 
Arrays.asList
ی که یه عضو داره
Collections.singletonList
رو پیشنهاد میده
اگه به نظرت اوکی بود ازینا بزار

2021-03-08 15:12 UTC, merged