Phase 04(c#)
Star-Academy/Winter99-Codestar-Reza-Adibi pull request #4
Opened 2021-03-06 16:48 UTC by RAAvenger

2021-03-08 08:09 UTC, MKasaei00 reviewed
کد خوبی بود. خسته نباشی
چند تا تغییر به نظرم رسید نوشتم
فقط به نظرم در کل یه مقداری بیش‌ از حد نیاز مسئله کلی پیاده کردی و پیاده‌سازی خیلی ساده‌تری هم امکان‌پذیر بود.

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/DataGetter.cs
> +    interface DataGetter {
طبق نام‌گذاری 
interface
باید با حرف 
I
شروع بشه
IDataGetter

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/FileReader.cs
> +            }
راه ساده‌تر و کوتاه‌تری هم برای خواندن متن فایل هست
‍‍‍``` 
File.ReadAllText(path)
```

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/FileReader.cs
> +            this.fileText = jsonTest;
به نظرم اگر تابع نتیجه برگردونه مناسب‌تره

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/MainClass.cs
> +        private static DataSorce[] dataSorces = new DataSorce[]{
املای درست
DataSource
:))

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/MainClass.cs
> +            }
به نظرم این قسمت کد برای تعریف مسئله‌ی فعلی یه مقدار پیچیده است.
و تا این حد پیچیدگی لازم نیست

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/DataReader.cs
> +    interface DataReader {
طبق روش نام‌گذاری اینترفیس‌ها باید حرف 
I
را اول اسم بذاری

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/ResultMaker.cs
> +        /// </returns>
به نظرم این کامنت خیلی لازم نیست
و از اسم و ورودی و خروجی واضحه که چه کاری انجام میشه

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/ResultMaker.cs
> +            List<Tuple<string, string, double>> lt = new List<Tuple<string, string, double>>();
اگر به جای 
tuple
از کلاس استفاده بشه فکر کنم مرتب‌تر میشه

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/MainClass.cs
> +                new ConsoleUI().DisplayObjects(bestStudents);
شی‌هایی که به صورت 
inline 
ایجاد می شن و بعد تابع فراخوانی میشه به نظرم زیاد تمیز نیست
بهتره که به صورت متغییر باشه

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/FileReader.cs
> +        public string fileText;
به نظرم فیلد‌های خاص یک کلاس نباید به صورت عمومی تعریف بشن

2021-03-08 08:09 UTC, MKasaei00 commented on Project-02/LocalDataBase.cs
> +        public Dictionary<string, object> datas;
به نظرم اگر نوع داده‌ی مشخص به جای
object 
ذکر بشه مناسب‌تره

2021-03-08 15:23 UTC, RAAvenger commented on Project-02/FileReader.cs
> +            this.fileText = jsonTest;
ذخیره‌ی اطلاعات فایل توی خود کلاس به نظرم منطقی اومد.

2021-03-08 15:32 UTC, RAAvenger commented on Project-02/MainClass.cs
> +            }
کار جالبی بود، خواستم تستش کنم.

2021-03-08 15:34 UTC, RAAvenger commented on Project-02/ResultMaker.cs
> +        /// </returns>
از این داکیومنتا صرفا برای این استفاده میکنم که خود 
ide
موقع نوشتن کد ازشون برای راهنمایی استفاده میکنه.

2021-03-08 15:45 UTC, RAAvenger commented on Project-02/FileReader.cs
> +        public string fileText;
برای تست اینجوریشون کردم، چون توی تست نمیتونی به فیلدای پروتکتد و پرایوت کلاسات دسترسی داشته باشی

2021-03-08 15:46 UTC, RAAvenger commented on Project-02/LocalDataBase.cs
> +        public Dictionary<string, object> datas;
اینجوری باید یه اینترفیس بزنم که دانشجو و امتیاز دانشجو ازش ارثبری کنن.
فکر نکنم یه اینترفیس خالی زدن برای این دوتا کار درستی باشه.

2021-03-08 18:05 UTC, mohammadhheidarzade approved these changes

2021-03-09 14:17 UTC, MRSadeghi78 reviewed
در کل خیلی خوب بود
خسته نباشی

2021-03-09 14:17 UTC, MRSadeghi78 commented on Project-02/ResultMaker.cs
> +        public IEnumerable<StudentGrade> GetTopStudents(int topStudentsCount = 3) {
این تابع به نظرم یه کم طولانیه
بهتره به چندتا تابع کوچکتر تقسیم بشه

2021-03-10 14:16 UTC, MKasaei00 approved these changes

2021-03-10 15:15 UTC, alrz1999 requested changes

2021-03-10 15:15 UTC, alrz1999 commented on Project-02/FileReader.cs
> +            this.fileText = jsonTest;
نفهمیدم چرا کلاسی که کارش خوندن فایله چرا باید اطلاعات فایلی که میخونه رو نگه داره؟

2021-03-10 15:15 UTC, alrz1999 commented on Project-02/IProgrammeDataBase.cs
> +    public interface IProgrammeDataBase {
IProgrammeDataBase?

2021-03-10 15:15 UTC, alrz1999 commented on Project-02/Student.cs
> +        public Student(int StudentNumber, string FirstName, string LastName) {
camelCase

2021-03-10 15:15 UTC, alrz1999 commented on Project-02/StudentScore.cs
> +        public StudentScore(int StudentNumber, string Lesson, double Score) {
camelCase

2021-03-13 08:30 UTC, MRSadeghi78 approved these changes

2021-03-13 16:48 UTC, alrz1999 commented on Project-02/LocalDataBase.cs
> +        public Dictionary<string, object> datas;
به نظرم یه اینترفیس بزاری قشنگ تر میشه

2021-03-13 16:48 UTC, alrz1999 approved these changes

2021-03-13 17:37 UTC, merged