Phase 08(entity frameworkwork core)
Star-Academy/Winter99-Codestar-Reza-Adibi pull request #9
Opened 2021-03-22 19:52 UTC by RAAvenger

2021-03-30 18:47 UTC, MKasaei00 reviewed
خسته نباشی 
چند مورد به ذهنم رسید نوشتم
ساختار خوبی نوشتی

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05/Or.cs
> +            return false;
به نظرم اگر اینجوری بنویسی تمیزتره
```csharp
return this.Token == or.Token
```

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05.Test/FileReaderTests.cs
> +        }
فکر می‌کنم به این تابع نیازی نیست و 
Dispose
خودکار فراخوانی میشه

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05.Test/GeneralFunctions.cs
> +            mockedDatabase.Setup(db => db.TryGetTokenDocumentIDs(token, out tokenDocumentIDs)).Returns(returnValue);
به نظرم این تابع کار خاصی انجام نمی‌ده و شاید ضروری نباشه

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05/Or.cs
> +            return false;
در کلاس‌های دیگه هم بعضا این مورد تکرار شده

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05/Tokenizer.cs
> +    public class Tokenizer {
به نظرم در طراحی این کلاس یه مسئله‌ای هست.

وقتی که ما قصد داریم یک داکیومنت را توکن کنیم تمام کلمات در این کلاس ذخیره می‌شوند و باقی‌می‌مانند در صورتی که نیازی به آن‌ها نداریم.
حتی بعد از خواندن تمام مقادیر باز هم تمام آرایه در حافظه باقی‌می‌ماند که ضروری نیست

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05/SqlDatabase.cs
> +    public class SqlDatabase : ProgramDatabase {
در این کلاس بعد از هر ریزعملیات 
savechanges
فراخوانی می‌شود که باعث تعداد ارتباط‌های زیاد با پایگاه داده می‌شود. و هم‌چنین در صورتی که یکی از دستورات میانی دچار خطا شود تغییرات قبلی در پایگاه داده ثبت شده و بازگردانی نمی‌شود.


به نظرم بهتر است بعد از اضافه شدن هر داکیومنت به پایگاه داده عملیات ذخیره‌سازی دائمی انجام شود تا در صورتی که موفق بود تمام سند به طور کامل ذخیره شود و در صورتی که موفق نبود تاثیر مخربی روی اطلاعات قبلی ایجاد نشود.

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05/ProgramDatabase.cs
> +    public enum DbmsName { SqlServer, Sqlite, Memory }
این نوعی وابستگی کلاس بالادستی به پایین دستی نیست؟
SOLID : Dependency inversion

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05/MainClass.cs
> +            foreach (KeyValuePair<string, string> pair in directoryData) {
به جای
`KeyValuePair<string, string>`
می‌تونیم
‍‍`var`
بذاریم

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05/MainClass.cs
> +            @"Server=localhost;Database=Codestar_Project05;Trusted_Connection=True;";
نام پایگاه داده و آدرس سرور به نظرم اگر یک متغییر دیگه باشد مرتب‌تر میشه

2021-03-30 18:47 UTC, MKasaei00 commented on Project-05/Project-05/And.cs
> +        [ExcludeFromCodeCoverage]
حذف به این شکل از
code coverage
برای توابع اصلی کلاس به نظرم مناسب نیست
(ممکنه با وجود کاورج 100 درصد باگ داشته باشیم(

2021-03-31 12:06 UTC, RAAvenger commented on Project-05/Project-05/Or.cs
> +            return false;
اینو درست میکنم، ولی به جز تمیزی مزیت دیگه‌ای هم داره؟

2021-03-31 12:44 UTC, RAAvenger commented on Project-05/Project-05.Test/FileReaderTests.cs
> +        }
با توجه به مطالبي که من خوندم  بهتره که این تابع توی مخرب صدا زده بشه

2021-03-31 12:44 UTC, RAAvenger commented on Project-05/Project-05.Test/GeneralFunctions.cs
> +            mockedDatabase.Setup(db => db.TryGetTokenDocumentIDs(token, out tokenDocumentIDs)).Returns(returnValue);
جهت تمیزیه

2021-03-31 13:38 UTC, RAAvenger commented on Project-05/Project-05/ProgramDatabase.cs
> +    public enum DbmsName { SqlServer, Sqlite, Memory }
<div dir="rtl">
سه تا تابع 
 InsertDataList، InsertData و TryGetTokenDocumentIDs
چندان به نوع پايگاه داده( inverted index یا sql database )
ارتباطی داشته باشن
</div>

2021-03-31 13:42 UTC, RAAvenger commented on Project-05/Project-05/MainClass.cs
> +            @"Server=localhost;Database=Codestar_Project05;Trusted_Connection=True;";
<div dir="rtl">
چونکه connectionString برای sqlServer، sqlite و memory کاملا متفاوتن به نظرم اومد بهتره این کار رو نکنم
</div>

2021-03-31 13:44 UTC, RAAvenger commented on Project-05/Project-05/And.cs
> +        [ExcludeFromCodeCoverage]
این تابع به طور خودکار ایجاد شده و جزو توابع اصلی کلاس محسوب نمیشه، صرفا برای این ایجاد شده که وارنینگ نگیرم

2021-03-31 14:32 UTC, MKasaei00 commented on Project-05/Project-05/Or.cs
> +            return false;
فکر کنم فقط تمیز‌تر و خواناتر میشه

2021-03-31 14:37 UTC, MKasaei00 commented on Project-05/Project-05/ProgramDatabase.cs
> +    public enum DbmsName { SqlServer, Sqlite, Memory }
منظورم اینه که 
DbmsName
وابسته به پیاده‌سازی‌های موجود هست و اگر نوع جدید اضافه بشه عملا این 
enum 
باید تغییر کنه و یک آیتم بهش اضافه بشه

راست‌ش من خودم راه خیلی خوبی برای حل مشکل به ذهنم نرسید
گفتم بنویسم شاید شما راه خوبی داشته باشی
خیلی هم مشکل مهمی نیست

2021-03-31 14:39 UTC, MKasaei00 commented on Project-05/Project-05/And.cs
> +        [ExcludeFromCodeCoverage]
به طور خودکار ایجاد شده ولی واقعا در عملکرد برنامه تاثیر داره 
وقتی که با هش‌لیست ها کار می‌کنیم این تابع خیلی مهم میشه

2021-03-31 14:47 UTC, RAAvenger commented on Project-05/Project-05/ProgramDatabase.cs
> +    public enum DbmsName { SqlServer, Sqlite, Memory }
<div dir="rtl">
اها، خب اره، اگر که یک نوع جدید اضافه بشه هم باید این enum تغییر کنه و هم یکی دو جای دیگه
</div>

2021-03-31 16:00 UTC, RAAvenger commented on Project-05/Project-05/Tokenizer.cs
> +    public class Tokenizer {
این رو تا حدودی مدیریت کردم، نظرت رو بده

2021-03-31 16:20 UTC, MKasaei00 commented on Project-05/Project-05/ProgramDatabase.cs
> +    public enum DbmsName { SqlServer, Sqlite, Memory }
اوکیه
ولی به نظرم اگر بیش‌تر بررسی کنی می‌تونی بهبود بدی و تغییر در کلاس فرزندان مستقل از کلاس پدر باشه

2021-03-31 16:20 UTC, MKasaei00 approved these changes

2021-04-01 18:51 UTC, MKasaei00 approved these changes
خسته نباشی
به نظرم خیلی بهتر شد

2021-04-01 18:51 UTC, MKasaei00 commented on Project-05/Project-05/SqlDatabase.cs
> +        protected bool saveOnInsert;
نام‌گذاری به سبک
PascalCase

2021-04-01 18:55 UTC, RAAvenger commented on Project-05/Project-05/SqlDatabase.cs
> +        protected bool saveOnInsert;
<div dir="rtl>
اینا field هستن
</div>

2021-04-01 19:08 UTC, MKasaei00 commented on Project-05/Project-05/SqlDatabase.cs
> +        protected bool saveOnInsert;
پیشنهاد 
rider
این بود که باید پاسکال باشه
چون به نوعی دسترسی عمومی برای کلاس فرزندان ایجاد میشه
هر طور می‌دونی

2021-04-03 08:09 UTC, mahdimalverdi requested changes

2021-04-03 08:09 UTC, mahdimalverdi commented on Project-05/Project-05/FileReader.cs
> +                foreach (string path in pathes)
از select استفاده کن
همچنین براکت هات هم بزار

2021-04-03 08:09 UTC, mahdimalverdi commented on Project-05/Project-05/IProgramDatabase.cs
> +    public enum DbmsName { SqlServer, Sqlite, Memory }
توی یه فایل دیگه بطاز

2021-04-03 08:09 UTC, mahdimalverdi commented on Project-05/Project-05/Migrations/SqlServerDatabaseContextModelSnapshot.cs
> +            modelBuilder
خیلی بزرگ شده بشکونش

2021-04-03 08:09 UTC, mahdimalverdi commented on Project-05/Project-05/Or.cs
> +        public override bool Equals(object obj) {
بین تابع هات فاصله بزار

2021-04-03 08:09 UTC, mahdimalverdi commented on Project-05/Project-05/Or.cs
> +            List<string> tokenDocuments;
نیای نیس اینو بنویسی

2021-04-03 08:09 UTC, mahdimalverdi commented on Project-05/Project-05/Or.cs
> +            if (database.TryGetTokenDocumentIDs(Token, out tokenDocuments))
بعد از out یه var اضافه کنی کافیه

2021-04-03 08:09 UTC, mahdimalverdi commented on Project-05/Project-05/SqlDatabase.cs
> +        protected bool saveOnInsert;
نه باید کمل کیس باشه

2021-04-03 08:44 UTC, MRSadeghi78 approved these changes
طبق معمول کد خیلی خوبی بود
چندتا مورد کوچیک
duplicate code
دیدم که نوشتم.
خسته نباشی

2021-04-03 08:44 UTC, MRSadeghi78 commented on Project-05/Project-05.Test/AndTests.cs
> +            var mickedDatabase = new Mock<IProgramDatabase>();
این ماک کردن دیتابیس رو اول اکثر توابع انجام دادی، شاید بهتر باشه بذاریش تو کانستراکتور

2021-04-03 08:44 UTC, MRSadeghi78 commented on Project-05/Project-05.Test/FileReaderTests.cs
> +        }
خود دایرکتوری رو حذف نمیکنی؟

2021-04-03 08:44 UTC, MRSadeghi78 commented on Project-05/Project-05.Test/InvertedIndexTests.cs
> +            var dataMap = new List<Tuple<string, string>> { new Tuple<string, string>("file1", "hello") };
دقیقا همین تعریف
dataMap
تو توابع دیگه این کلاس هم هست، یه جورایی
duplicate code
محسوب میشه. به نظرم بهتره بذاریش تو یه تابع و هربار اون رو صدا کنی

2021-04-03 13:47 UTC, mohammadhheidarzade approved these changes

2021-04-04 10:01 UTC, RAAvenger commented on Project-05/Project-05/FileReader.cs
> +                foreach (string path in pathes)
<div dir="rtl">
select رو توضیح میدی؟
</div>

2021-04-04 10:18 UTC, RAAvenger commented on Project-05/Project-05/Or.cs
> +            List<string> tokenDocuments;
<div dir="rtl">
این دوتا لیست باید با هم اجتماع بشن، اولی که نمیتونه null باشه و دومی هم توی خط 20 مقدار میگیره
</div>

2021-04-04 10:28 UTC, RAAvenger commented on Project-05/Project-05.Test/AndTests.cs
> +            var mickedDatabase = new Mock<IProgramDatabase>();
چونکه توی تمام تست‌ها احتیاجی به این کار نیست به نظرم اومد که بهتره که توی کانستراکتور دیتابیس رو ماک نکنم

2021-04-04 10:51 UTC, RAAvenger commented on Project-05/Project-05.Test/InvertedIndexTests.cs
> +            var dataMap = new List<Tuple<string, string>> { new Tuple<string, string>("file1", "hello") };
درسته، ولي چون مقادير براي هر تست متفاوت هستن اگر که بخوام اين تعريف متغيير رو ببرم توي يک تابع ديگه باز بايد بخش بزرگي از اين کدا رو موقع صدا زدن تابع بنويسم و عملا تعريف تابع تغييري ايجاد نميکنه

2021-04-10 10:14 UTC, alrz1999 commented on Project-05( Entity Framework Core )/Project-05/Tokenizer.cs
> +            var documentIdTokenPairs = new List<Tuple<string, string>>();
این 
Tuple
 رو به نظرم اگه یه کلاس کنی بهتره تا هم جاهای دیگه معلوم باشه توش چی هست هم اگه بعدا خواستی چیزی بهش اضافه کنی بزرگ نشه

2021-04-10 10:14 UTC, alrz1999 commented on Project-05( Entity Framework Core )/Project-05/SqlDatabase.cs
> +            var tokenDocuments = theToken == null ? null : theToken.Documents;
`theToken?.Documents` = `theToken == null ? null : theToken.Documents`

2021-04-10 10:14 UTC, alrz1999 commented on Project-05( Entity Framework Core )/Project-05.Test/SqlDatabaseTests.cs
> +        private static readonly Semaphore isRunningCountLock = new Semaphore(1, 1);
تست های تو یک کلاس به صورت 
Sequential
اجرا میشن و اینجا میتونی استفاده نکنی

2021-04-10 10:14 UTC, alrz1999 commented on Project-05( Entity Framework Core )/Project-05/Document.cs
> +        [ExcludeFromCodeCoverage]
چرا exclude?

2021-04-10 10:14 UTC, alrz1999 commented on Project-05( Entity Framework Core )/Project-05/Searcher.cs
> +            var firstOperatorIsAnd = operators.ElementAt(0).GetType() == typeof(And);
میشه جای این از
is
هم استفاده کرد ولی اینجا فرقی نداره
https://stackoverflow.com/questions/983030/type-checking-typeof-gettype-or-is

2021-04-17 20:27 UTC, RAAvenger commented on Project-05( Entity Framework Core )/Project-05/Document.cs
> +        [ExcludeFromCodeCoverage]
فکر کردم که چیز مهمی نیستن، اشتباه میکردم :).

2021-04-23 05:19 UTC, alrz1999 approved these changes

2021-05-01 09:28 UTC, merged